name: Network Tests

on:
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest-ppc64le

    steps:
      - name: Check runner
        run: |
          uname -a
          podman --version

      - name: Speedtest in Podman
        run: |
          podman run --rm --network host speedtest/speedtest:latest
